### ISSUE TITLE
android如何使用，会报错啊

### ISSUE THREAD

**Issue by wudaotiantian** [killme2008/aviatorscript#29]

**Comment by killme2008** [comment]
请告知具体的错误信息。

**Comment by wudaotiantian** [comment]
08-14 17:28:46.224 12932-12932/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.example.myapplication, PID: 12932
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.myapplication/com.example.myapplication.MainActivity}: com.googlecode.aviator.exception.CompileExpressionErrorException: define class error
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2184)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:135)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
                                                       at dalvik.system.NativeStart.main(Native Method)
                                                    Caused by: com.googlecode.aviator.exception.CompileExpressionErrorException: define class error
                                                       at com.googlecode.aviator.code.asm.ASMCodeGenerator.getResult(ASMCodeGenerator.java:678)
                                                       at com.googlecode.aviator.code.OptimizeCodeGenerator.getResult(OptimizeCodeGenerator.java:360)
                                                       at com.googlecode.aviator.parser.ExpressionParser.parse(ExpressionParser.java:702)
                                                       at com.googlecode.aviator.AviatorEvaluator.innerCompile(AviatorEvaluator.java:518)
                                                       at com.googlecode.aviator.AviatorEvaluator.compile(AviatorEvaluator.java:497)
                                                       at com.googlecode.aviator.AviatorEvaluator.execute(AviatorEvaluator.java:605)
                                                       at com.googlecode.aviator.AviatorEvaluator.execute(AviatorEvaluator.java:623)
                                                       at com.example.myapplication.MainActivity.onCreate(MainActivity.java:36)
                                                       at android.app.Activity.performCreate(Activity.java:5231)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233) 
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:136) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
                                                    Caused by: java.lang.UnsupportedOperationException: can't load this type of class file
                                                       at java.lang.ClassLoader.defineClass(ClassLoader.java:253)
                                                       at com.googlecode.aviator.parser.AviatorClassLoader.defineClass(AviatorClassLoader.java:35)
                                                       at com.googlecode.aviator.code.asm.ASMCodeGenerator.getResult(ASMCodeGenerator.java:673)
                                                       at com.googlecode.aviator.code.OptimizeCodeGenerator.getResult(OptimizeCodeGenerator.java:360) 
                                                       at com.googlecode.aviator.parser.ExpressionParser.parse(ExpressionParser.java:702) 
                                                       at com.googlecode.aviator.AviatorEvaluator.innerCompile(AviatorEvaluator.java:518) 
                                                       at com.googlecode.aviator.AviatorEvaluator.compile(AviatorEvaluator.java:497) 
                                                       at com.googlecode.aviator.AviatorEvaluator.execute(AviatorEvaluator.java:605) 
                                                       at com.googlecode.aviator.AviatorEvaluator.execute(AviatorEvaluator.java:623) 
                                                       at com.example.myapplication.MainActivity.onCreate(MainActivity.java:36) 
                                                       at android.app.Activity.performCreate(Activity.java:5231) 
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233) 
                                                       at android.app.ActivityThread.access$800(ActivityThread.java:135) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:136) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5001) 
                                                       at java.lang.reflect.Method.invokeNative(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:515) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609) 
                                                       at dalvik.system.NativeStart.main(Native Method) 
08-14 17:28:55.908 478-492/system_process E/WindowManager: Starting window AppWindowToken{52c36060 token=Token{5293cd08 ActivityRecord{529f1f2c u0 com.example.myapplication/.MainActivity t32}}} timed out
08-14 17:29:26.704 1248-13077/com.estrongs.android.pop E/Cataloger: syncFile:/storage/emulated/0/Android/data/com.tencent.news/files/onlinelog/pushProcess_2017.08.14.txt
08-14 17:32:33.064 1248-13582/com.estrongs.android.pop E/Cataloger: syncFile:/storage/emulated/0/Android/data/com.tencent.news/files/onlinelog/pushProcess_2017.08.14.txt

**Comment by killme2008** [comment]
sorry，我没有仔细看标题。不支持 android 的。

**Comment by wxb871127** [comment]
我晕 看完了开发文档 才发现不支持android ...

**Comment by killme2008** [comment]
准备在 android 下支持纯解释模型

**Comment by killme2008** [comment]
android 有 dexmaker，计划学习下，可能可以在 android 也支持编译成字节码 https://github.com/linkedin/dexmaker

**Comment by killme2008** [comment]
已支持解释模式，发布了 5.3.0-beta 版本，欢迎测试 https://github.com/killme2008/aviatorscript/releases/tag/aviator-5.3.0-beta

例子 https://github.com/killme2008/aviatorscript/blob/master/src/test/java/com/googlecode/aviator/example/InterpreterExample.java
文档 https://www.yuque.com/boyan-avfmj/aviatorscript/ok8agx
