### ISSUE TITLE
多重引号引起的异常

### ISSUE THREAD

**Issue by qiuweili123** [killme2008/aviatorscript#318]
表达式为：fromMobile!=userMobile && arrayOneTrue(toInfo,'(obj.toMobile!=obj.toMobile2 || obj.amount>=100) && matches(obj.remark,"'买酒'")')，在运行的时候就报错，19:18:39.666 [main] ERROR com.ishansong.ops.rinet.util.RuleEngineUtil - fireRules error exps:fromMobile!=userMobile && arrayOneTrue(toInfo,'(obj.toMobile!=obj.toMobile2 || obj.amount>=100) && matches(obj.remark,"'买酒'")'),params:{userMobile=13011112223, toInfo=[{toMobile2=15800001112, amount=200, toMobile=15800001111, remark=买1酒}, {toMobile2=15800001112, amount=50, toMobile=15800001111, remark=买1烟}], fromMobile=13011112222}
com.googlecode.aviator.exception.ExpressionSyntaxErrorException: Syntax error: insert ')' to complete statement at 46, lineNumber: 1, token : [type='String',lexeme='(obj.toMobile!=obj.toMobile2 || obj.amount>=100) && matches(obj.remark,"',index=46],
while parsing expression: `
fromMobile!=userMobile && arrayOneTrue(toInfo,'(obj.toMobile!=obj.toMobile2 || obj.amount>=100) && matches(obj.remark,"'买酒^^^
`
	at com.googlecode.aviator.AviatorEvaluatorInstance.innerCompile(AviatorEvaluatorInstance.java:1297)
	at com.googlecode.aviator.AviatorEvaluatorInstance.compile(AviatorEvaluatorInstance.java:1260)
	at com.googlecode.aviator.AviatorEvaluatorInstance.compile(AviatorEvaluatorInstance.java:1211)
	at com.googlecode.aviator.AviatorEvaluatorInstance.execute(AviatorEvaluatorInstance.java:1387)
	at com.googlecode.aviator.AviatorEvaluator.execute(AviatorEvaluator.java:509)
	at com.googlecode.aviator.AviatorEvaluator.execute(AviatorEvaluator.java:521)
	at com.ishansong.ops.rinet.util.RuleEngineUtil.fireRules(RuleEngineUtil.java:37)
	at com.ishansong.ops.rinet.util.RuleFormulaUtilTest.testFillFormulaObjArray(RuleFormulaUtilTest.java:289)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

 这种问题表达式中还有引号，该如何处理？

**Comment by killme2008** [comment]
请转义，参考 https://www.yuque.com/boyan-avfmj/aviatorscript/lvabnw#817bb
