### ISSUE TITLE
aviator 5.2.0版本，遇到初始化错误导致的问题

### ISSUE THREAD

**Issue by GuoYaxiang** [killme2008/aviatorscript#331]
在使用aviator 5.2.0版本时，遇到初始化错误导致的问题。
测试代码简化如下：
![image](https://user-images.githubusercontent.com/20477162/102197079-a623a780-3efb-11eb-854d-6b9a4b7b80e4.png)
本机环境JDK8，使用5.1.4版本时，执行正常；使用5.2.0版本时，出错的堆栈信息如下：

java.lang.ExceptionInInitializerError
	at com.googlecode.aviator.AviatorEvaluator.getInstance(AviatorEvaluator.java:100)
	at com.googlecode.aviator.AviatorEvaluator.<clinit>(AviatorEvaluator.java:60)
	at com.tencent.apaas.expression.SimpleExpressionTest.testAviator(SimpleExpressionTest.java:188)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Caused by: com.googlecode.aviator.exception.ExpressionRuntimeException: Can't assign value to exports.take_while
	at com.googlecode.aviator.runtime.type.AviatorJavaType.setProperty(AviatorJavaType.java:414)
	at com.googlecode.aviator.runtime.type.AviatorJavaType.setValue(AviatorJavaType.java:397)
	at Script_1608024566823_0/454841229.execute0(Script_1608024566823_0:124)
	at com.googlecode.aviator.ClassExpression.executeDirectly(ClassExpression.java:65)
	at com.googlecode.aviator.BaseExpression.execute(BaseExpression.java:136)
	at com.googlecode.aviator.AviatorEvaluatorInstance.executeModule(AviatorEvaluatorInstance.java:347)
	at com.googlecode.aviator.AviatorEvaluatorInstance.loadInternalLibs(AviatorEvaluatorInstance.java:1024)
	at com.googlecode.aviator.AviatorEvaluatorInstance.loadLib(AviatorEvaluatorInstance.java:895)
	at com.googlecode.aviator.AviatorEvaluatorInstance.<init>(AviatorEvaluatorInstance.java:1065)
	at com.googlecode.aviator.AviatorEvaluator$StaticHolder.<clinit>(AviatorEvaluator.java:90)
	... 34 more
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/beanutils/BeanIntrospector
	at com.googlecode.aviator.runtime.type.AviatorJavaType.setProperty(AviatorJavaType.java:409)
	... 43 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.beanutils.BeanIntrospector
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 44 more

PS：
5.2.1版本遇到相同的问题。

**Comment by killme2008** [comment]
这个错误信息很明显了

```
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/beanutils/BeanIntrospector
at com.googlecode.aviator.runtime.type.AviatorJavaType.setProperty(AviatorJavaType.java:409)
... 43 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.beanutils.BeanIntrospector
```

应该就是 commons-beanutils 版本冲突
