### ISSUE TITLE
junit 版本太低，无法在 intellij 中单独运行测试用例

### ISSUE THREAD

**Issue by DQinYuan** [killme2008/aviatorscript#353]
![image](https://user-images.githubusercontent.com/23725000/106636915-38236480-65bd-11eb-8564-57c74bcf53ba.png)

在 maven 中是可以运行测试用例的，但是在 idea 中无法单独运行(所有单元测试都是这样这)，猜测是因为 junit 版本太低，导致和 idea 的 junit-launch 无法启动？

```
Exception in thread "main" java.lang.NoSuchMethodError: org.junit.runner.Description.createSuiteDescription(Ljava/lang/String;[Ljava/lang/annotation/Annotation;)Lorg/junit/runner/Description;
	at com.intellij.junit4.JUnit4TestListener.testStarted(JUnit4TestListener.java:115)
	at com.intellij.junit4.JUnit4TestListener.testStarted(JUnit4TestListener.java:92)
	at org.junit.runner.notification.RunNotifier$3.notifyListener(RunNotifier.java:83)
	at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:37)
	at org.junit.runner.notification.RunNotifier.fireTestStarted(RunNotifier.java:80)
	at org.junit.internal.runners.TestMethodRunner.run(TestMethodRunner.java:39)
	at org.junit.internal.runners.TestClassMethodsRunner.invokeTestMethod(TestClassMethodsRunner.java:66)
	at org.junit.internal.runners.TestClassMethodsRunner.run(TestClassMethodsRunner.java:35)
	at org.junit.internal.runners.TestClassRunner$1.runUnprotected(TestClassRunner.java:42)
	at org.junit.internal.runners.BeforeAndAfterRunner.runProtected(BeforeAndAfterRunner.java:34)
	at org.junit.internal.runners.TestClassRunner.run(TestClassRunner.java:52)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:130)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
```

**Comment by DQinYuan** [comment]
经过测试，升级到 4.12 能解决这个问题

**Comment by killme2008** [comment]
已经发布 5.2.4，感谢 https://github.com/killme2008/aviatorscript/releases/tag/aviator-5.2.4
