### ISSUE TITLE
字符串表达式编译复杂语句报错

### ISSUE THREAD

**Issue by iPush** [killme2008/aviatorscript#371]
版本 5.2.1

表达式原文为：
a = 100; if (a > 50) { 1 } else { 2 }

---
当使用 compileScript 方法时
```
Expression exp = AviatorEvaluator.getInstance().compileScript("examples/multi_if.av");
```
运行正确

当使用 compile 方法时候，运行异常

```
@Test
    public void testIfStatements() {
        String exp = "a = 100; if (a > 50) { 1 } else { 2 }";
        Long res = (Long) AviatorEvaluator.getInstance().compile(exp).execute();
        System.out.print(res);
    }
```

异常日志：

com.googlecode.aviator.exception.ExpressionSyntaxErrorException: Syntax error:Unexpect token '{' at 21, current token: [type='Char',lexeme='{',index=21]. Parsing expression: `a = 100; if (a > 50) {^^`

	at com.googlecode.aviator.parser.ExpressionParser.reportSyntaxError(ExpressionParser.java:765)
	at com.googlecode.aviator.parser.ExpressionParser.parse(ExpressionParser.java:791)
	at com.googlecode.aviator.AviatorEvaluatorInstance.innerCompile(AviatorEvaluatorInstance.java:673)
	at com.googlecode.aviator.AviatorEvaluatorInstance.compile(AviatorEvaluatorInstance.java:653)
	at com.googlecode.aviator.AviatorEvaluatorInstance.compile(AviatorEvaluatorInstance.java:714)
	at com.bytedance.rc.marlindispatcher.aviator.TestExpression.testIfStatements(TestExpression.java:612)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)

Process finished with exit code 255

**Comment by killme2008** [comment]
```java
package com.googlecode.aviator.example;

import com.googlecode.aviator.AviatorEvaluator;


public class SimpleExample {
  public static void main(final String[] args) throws Exception {
    String exp = "a = 100; if (a > 50) { 1 } else { 2 }";
    Long res = (Long) AviatorEvaluator.getInstance().compile(exp).execute();
    System.out.print(res);
  }
}

```

执行输出：
```
1
```

**Comment by killme2008** [comment]
你看看你的 classpath 是不是存在多个版本的 aviator 吧。
