### ISSUE TITLE
自定义函数，表达式参数值是文件路径，编译或执行报错

### ISSUE THREAD

**Issue by lematechx** [killme2008/aviatorscript#378]
# 测试案例： 
@Test
    public void testFileExp(){
        AviatorEvaluator.addFunction(new BuiltInAviatorEvaluator.BuiltInFunctionParameterize());
        String filePath = "/Users/lematechx/Desktop/resources/data/csvFile.csv";
        //parameterize()：自定义函数
        System.out.println(AviatorEvaluator.execute("parameterize("+filePath+")"));
   }
 /**
     * built-in $P
     */
    public static class BuiltInFunctionParameterize extends AbstractFunction {
        @Override
        public AviatorObject call(Map<String, Object> env, AviatorObject csvFilePathObj) {
            if (Objects.isNull(csvFilePathObj) || StrUtil.isEmpty(csvFilePathObj.toString())) {
                String exceptionMsg = String.format("The CVS file path cannot be empty");
                throw new DefinedException(exceptionMsg);
            }
 @Override
        public String getName() {
            return "parameterize";
        }
}

# 报错信息：

com.googlecode.aviator.exception.ExpressionSyntaxErrorException: Syntax error: insert ')' to complete statement at 8, lineNumber: 1, token : [type='Char',lexeme='/',index=8],
while parsing expression: `
P(/Users/lematechx^^^
`

	at com.googlecode.aviator.AviatorEvaluatorInstance.innerCompile(AviatorEvaluatorInstance.java:1494)
	at com.googlecode.aviator.AviatorEvaluatorInstance.compile(AviatorEvaluatorInstance.java:1455)
	at com.googlecode.aviator.AviatorEvaluatorInstance.compile(AviatorEvaluatorInstance.java:1413)
	at com.googlecode.aviator.AviatorEvaluatorInstance.compile(AviatorEvaluatorInstance.java:1400)
	at com.googlecode.aviator.AviatorEvaluatorInstance.execute(AviatorEvaluatorInstance.java:1601)
	at com.googlecode.aviator.AviatorEvaluator.execute(AviatorEvaluator.java:521)
	at com.googlecode.aviator.AviatorEvaluator.execute(AviatorEvaluator.java:533)
	at com.googlecode.aviator.AviatorEvaluator.execute(AviatorEvaluator.java:554)
	at io.lematech.httprunner4j.junit.dataconstructor.DCTest.testFileExp(DCTest.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)

# 期望

当前输出是文件路径，可以直接当String处理

**Comment by killme2008** [comment]
你把你的表达式输出下就知道为啥了。
