### ISSUE TITLE
map作为数据源，其中key为数字时，程序直接报错。

### ISSUE THREAD

**Issue by vampireslove** [killme2008/aviatorscript#406]
// key 有数字  43980，程序直接报错。
com.googlecode.aviator.exception.ExpressionSyntaxErrorException: Syntax error: illegal identifier: 43980 at 17, lineNumber: 1, token : [type='variable',lexeme='status.43980.test',index=0],
while parsing expression: `
status.43980.test^^^
`
	at com.googlecode.aviator.AviatorEvaluatorInstance.innerCompile(AviatorEvaluatorInstance.java:1494)
	at com.googlecode.aviator.AviatorEvaluatorInstance.compile(AviatorEvaluatorInstance.java:1455)
	at com.googlecode.aviator.AviatorEvaluatorInstance.compile(AviatorEvaluatorInstance.java:1413)
	at com.googlecode.aviator.AviatorEvaluatorInstance.compile(AviatorEvaluatorInstance.java:1400)
	at com.googlecode.aviator.AviatorEvaluator.compile(AviatorEvaluator.java:473)
	at com.googlecode.aviator.AviatorEvaluator.compile(AviatorEvaluator.java:484)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)

       @Test
	public void aviatorJsonTest4() throws JsonParseException, JsonMappingException, IOException {
		String data = "{\r\n" + 
				"  \"status\": {\r\n" + 
				"    \"43980\": {\r\n" + 
				"      \"test\": \"ok\"\r\n" + 
				"    }\r\n" + 
				"  }\r\n" + 
				"}";
	    ObjectMapper mapper = new ObjectMapper();
	    HashMap da= mapper.readValue(data, HashMap.class);
	    String expression="status.43980.test ==\"ok\"";
	    Expression compiledExp = AviatorEvaluator.compile(expression); 
	   System.out.println(compiledExp.execute(da)); 
	}

	// key  是字符，程序正常运行。
	@Test
	public void aviatorJsonTest5() throws JsonParseException, JsonMappingException, IOException {
		String data = "{\r\n" + 
				"  \"status\": {\r\n" + 
				"    \"haha\": {\r\n" + 
				"      \"test\": \"ok\"\r\n" + 
				"    }\r\n" + 
				"  }\r\n" + 
				"}";
	    ObjectMapper mapper = new ObjectMapper();
	    HashMap da= mapper.readValue(data, HashMap.class);
	    String expression="status.haha.test ==\"ok\"";
	    Expression compiledExp = AviatorEvaluator.compile(expression); 
	   System.out.println(compiledExp.execute(da)); 
	}

**Comment by happyguy1986** [comment]
String expression="status.\"43980\".test ==\"ok\"";  这种方式试下

**Comment by killme2008** [comment]
key 要求是合法的变量名，如果不是，用 quote 变量名的方式：

```
#status.43980.test
```

文档其实都有写。
