### ISSUE TITLE
aviator版本升级（5.0.0-beta2 -》 5.3.0）失败（fastjson报脚本异常）

### ISSUE THREAD

**Issue by yeshangqiu** [killme2008/aviatorscript#435]
exec task exception,  com.alibaba.fastjson.JSONException: create asm serializer error, verson 1.2.70, class class Script_1642403337546_403/1890091435
  at com.alibaba.fastjson.serializer.SerializeConfig.createJavaBeanSerializer(SerializeConfig.java:264)
  at com.alibaba.fastjson.serializer.SerializeConfig.createJavaBeanSerializer(SerializeConfig.java:120)
  at com.alibaba.fastjson.serializer.SerializeConfig.getObjectWriter(SerializeConfig.java:799)
  at com.alibaba.fastjson.serializer.SerializeConfig.getObjectWriter(SerializeConfig.java:436)
  at com.alibaba.fastjson.serializer.JSONSerializer.getObjectWriter(JSONSerializer.java:416)
  at com.alibaba.fastjson.serializer.JSONSerializer.writeWithFieldName(JSONSerializer.java:331)
  at com.alibaba.fastjson.serializer.ASMSerializer_38_LambdaFunction.write(Unknown Source)
  at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:271)
  at com.alibaba.fastjson.serializer.MapSerializer.write(MapSerializer.java:44)
  at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:285)
  at com.alibaba.fastjson.JSON.toJSONString(JSON.java:758)
  at com.alibaba.fastjson.JSON.toJSONString(JSON.java:696)
  at com.alibaba.fastjson.JSON.toJSONString(JSON.java:661)
  ..........
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at com.alibaba.ttl.TtlRunnable.run(TtlRunnable.java:51)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: IllegalName: com.alibaba.fastjson.serializer.ASMSerializer_39_Script_1642403337546_403/1890091435
  at java.lang.ClassLoader.preDefineClass(ClassLoader.java:654)
  at java.lang.ClassLoader.defineClass(ClassLoader.java:761)
  at com.alibaba.fastjson.util.ASMClassLoader.defineClassPublic(ASMClassLoader.java:174)
  at com.alibaba.fastjson.serializer.ASMSerializerFactory.createJavaBeanSerializer(ASMSerializerFactory.java:409)
  at com.alibaba.fastjson.serializer.SerializeConfig.createASMSerializer(SerializeConfig.java:92)
  at com.alibaba.fastjson.serializer.SerializeConfig.createJavaBeanSerializer(SerializeConfig.java:248)
  ... 34 more

**Comment by yeshangqiu** [comment]
fastjson版本升级至 1.2.70

**Comment by killme2008** [comment]
这跟aviator没啥关系，class not found 如果不是缺少 jar，就一般是类库版本冲突，自己查吧。
