### ISSUE TITLE
生成的动态class文件能否有个配置或者开关可以持久化成1个文件

### ISSUE THREAD

**Issue by zxhdaniel** [killme2008/aviatorscript#452]
否则抛出这样的异常，不知道从何下手：
java.lang.NullPointerException: null
 at Script_1647260545963_11/1962957308.execute0(Unknown Source)
 at com.googlecode.aviator.ClassExpression.executeDirectly(ClassExpression.java:65)
 at com.googlecode.aviator.BaseExpression.execute(BaseExpression.java:92)

表达式非常简单，就是自己实现了1个自定义函数max，然后用max(a)-max(b)-max(c)，就抛出这样的异常，有点难解...

**Comment by zxhdaniel** [comment]
后来调试自己的代码后，发现空指针是自己代码里面抛出来的。。。所以，上面这个，仅仅建议建议哈。

**Comment by zxhdaniel** [comment]
后来调试自己的代码后，发现空指针是自己代码里面抛出来的。。。所以，上面这个，仅仅建议建议哈。

**Comment by killme2008** [comment]
调试问题的时候，可以打开 `Options.TRACE_EVAL` 选项跟踪执行过程。 目前已经支持错误定位到行的，但是如果你的代码就一行，那肯定起不了什么帮助。
