### ISSUE TITLE
与或非计算  非运算符不支持0/1

### ISSUE THREAD

**Issue by a937282042** [killme2008/aviatorscript#490]
代码如下
`
        String expression="!c";
        Map param=new HashMap();
        param.put("c",0);
        System.out.println(expression);
        Expression compiledExp = AviatorEvaluator.compile(expression);
`
执行报错
`Exception in thread "main" com.googlecode.aviator.exception.ExpressionRuntimeException: <JavaType, c, 0, java.lang.Integer> doesn't support not operation '!'
	at com.googlecode.aviator.runtime.type.AviatorObject.not(AviatorObject.java:137)
	at com.googlecode.aviator.runtime.type.AviatorJavaType.not(AviatorJavaType.java:626)
	at Script_1662689545697_58/796684896.execute0(Script_1662689545697_58:1)
	at com.googlecode.aviator.ClassExpression.executeDirectly(ClassExpression.java:44)
	at com.googlecode.aviator.BaseExpression.execute(BaseExpression.java:246)
	at com.thpower.formula.aviator.AviatorFormula.main(AviatorFormula.java:58)`

**Comment by killme2008** [comment]
文档从来没有说过整数也支持逻辑运算符吧？ 有需要，自己重载好了。

**Comment by a937282042** [comment]
嗯嗯，我觉得后续版本可以支持一下加一个 变量判断可以

**Comment by killme2008** [comment]
sorry，这个不准备直接支持，不是一个常见的特性。并且有需要的朋友可以通过重载运算符实现。
