### ISSUE TITLE
无法通过.访问list元素的属性

### ISSUE THREAD

**Issue by movee8** [killme2008/aviatorscript#565]
我有一个代码片段：
```
String jsonStr = """
                {
                    "a": {
                        "b": [
                                {
                                    "x": 3
                                },
                                {
                                    "x": 4
                                }
                            ]
                    }
                }
                """;


  JSONObject jsonObj = new JSONObject(jsonStr);
  Object value = AviatorEvaluator.execute("a.b[0].x", jsonObj.toMap());
```
执行时会报错：
```
com.googlecode.aviator.exception.ExpressionSyntaxErrorException: Syntax error: unexpect token ']', maybe forget to insert ';' to complete last expression  at 5, lineNumber: 1, token : [type='Char',lexeme=']',index=5],
while parsing expression: `
a.b[0]^^^
`
	at com.googlecode.aviator.AviatorEvaluatorInstance.innerCompile(AviatorEvaluatorInstance.java:1545) ~[aviator-5.3.3.jar:na]
	at com.googlecode.aviator.AviatorEvaluatorInstance.compile(AviatorEvaluatorInstance.java:1506) ~[aviator-5.3.3.jar:na]
	at com.googlecode.aviator.AviatorEvaluatorInstance.compile(AviatorEvaluatorInstance.java:1464) ~[aviator-5.3.3.jar:na]
	at com.googlecode.aviator.AviatorEvaluatorInstance.compile(AviatorEvaluatorInstance.java:1451) ~[aviator-5.3.3.jar:na]
	at com.googlecode.aviator.AviatorEvaluatorInstance.execute(AviatorEvaluatorInstance.java:1668) ~[aviator-5.3.3.jar:na]
	at com.googlecode.aviator.AviatorEvaluatorInstance.execute(AviatorEvaluatorInstance.java:1685) ~[aviator-5.3.3.jar:na]
	at com.googlecode.aviator.AviatorEvaluator.execute(AviatorEvaluator.java:544) ~[aviator-5.3.3.jar:na]
	at movee.aviator.AviatorApplication.lambda$test$0(AviatorApplication.java:79) ~[classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771) ~[spring-boot-3.1.2.jar:3.1.2]
	... 5 common frames omitted
```
将表达式改为[]访问属性，才会正常：
```
Object value = AviatorEvaluator.execute("a.b[0].['x']", jsonObj.toMap());
```

请问上述现象符合设计初衷吗？是否可以优化一下，list元素的属性也可以通过 . 访问？

**Comment by killme2008** [comment]
5.4.4 已发布,现在支持不带 `#` 前缀直接用 `.` 访问对象属性和 list 元素,例如 `foo.bars[0].name`。已同步到 Maven Central:`com.googlecode.aviator:aviator:5.4.4`。

Release notes: https://github.com/killme2008/aviatorscript/releases/tag/aviator-5.4.4
