### ISSUE TITLE
获取List集合中的某个元素后，再获取元素的某个属性会报错

### ISSUE THREAD

**Issue by moqiaaa** [killme2008/aviatorscript#603]
![4abe67af8a62636dc2733c9db69189a](https://github.com/killme2008/aviatorscript/assets/129827905/576b9c16-d808-4d4c-8708-2fcc2f147741)
![98a348ee4ae1ae86672a4fe2d7f7f6c](https://github.com/killme2008/aviatorscript/assets/129827905/aea334a6-9157-4c8c-b163-e9d36f6ce5cd)
com.googlecode.aviator.exception.ExpressionSyntaxErrorException: Syntax error: insert ')' to complete statement at 29, lineNumber: 1, token : [type='Char',lexeme=')',index=29],
while parsing expression: `
print((seq.get(o.oprninfos,0))^^^
`
	at com.googlecode.aviator.AviatorEvaluatorInstance.innerCompile(AviatorEvaluatorInstance.java:1505)
	at com.googlecode.aviator.AviatorEvaluatorInstance.access$000(AviatorEvaluatorInstance.java:186)
	at com.googlecode.aviator.AviatorEvaluatorInstance$2.call(AviatorEvaluatorInstance.java:1478)
	at com.googlecode.aviator.AviatorEvaluatorInstance$2.call(AviatorEvaluatorInstance.java:1475)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.googlecode.aviator.AviatorEvaluatorInstance.compile(AviatorEvaluatorInstance.java:1462)
	at com.googlecode.aviator.AviatorEvaluatorInstance.compile(AviatorEvaluatorInstance.java:1426)
	at com.googlecode.aviator.AviatorEvaluatorInstance.execute(AviatorEvaluatorInstance.java:1625)
	at com.googlecode.aviator.AviatorEvaluatorInstance.execute(AviatorEvaluatorInstance.java:1642)
	at com.googlecode.aviator.AviatorEvaluator.execute(AviatorEvaluator.java:558)
	at com.fusion.CustomCommand.ruleMedicalRecordTest(CustomCommand.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)

**Comment by kongxiangxin** [comment]
closed? why

**Comment by killme2008** [comment]
5.4.4 起,变量上的属性链 + 数组下标已原生支持,取 list 元素属性可以直接写(实测通过):

```
o.oprninfos[0].name
```

不必再用 `seq.get(o.oprninfos, 0)` 之后再取属性。

提示:在函数调用返回值上直接接 `.prop`(如 `seq.get(o.oprninfos,0).name`)目前仍不支持,请改用上面的变量属性链写法。

Maven Central:`com.googlecode.aviator:aviator:5.4.4`
