### ISSUE TITLE
java 9+ entry.key、entry.value异常

### ISSUE THREAD

**Issue by zengnm** [killme2008/aviatorscript#632]
我使用jdk17编译后执行单测：
com.googlecode.aviator.test.function.FunctionTest#testSeqFunction

    com.googlecode.aviator.exception.ExpressionRuntimeException: Could not find variable x.value 
	      at com.googlecode.aviator.runtime.type.AviatorJavaType.getProperty(AviatorJavaType.java:465)
	      at com.googlecode.aviator.runtime.type.AviatorJavaType.getValueFromEnv(AviatorJavaType.java:355)
	      at com.googlecode.aviator.runtime.type.AviatorJavaType.getValue(AviatorJavaType.java:338)
	      at AviatorScript_1718265308683_115.execute0(AviatorScript_1718265308683_115:1)
	      at com.googlecode.aviator.ClassExpression.executeDirectly(ClassExpression.java:55)
	      at com.googlecode.aviator.runtime.function.LambdaFunction.call(LambdaFunction.java:129)
	      at com.googlecode.aviator.runtime.function.seq.SeqMapFunction.call(SeqMapFunction.java:61)
	      at AviatorScript_1718265308683_114.execute0(AviatorScript_1718265308683_114:1)
	      at com.googlecode.aviator.ClassExpression.executeDirectly(ClassExpression.java:55)
	      at com.googlecode.aviator.BaseExpression.execute(BaseExpression.java:268)
	      at com.googlecode.aviator.BaseExpression.execute(BaseExpression.java:255)
	      at com.googlecode.aviator.AviatorEvaluatorInstance.execute(AviatorEvaluatorInstance.java:1674)
	      at com.googlecode.aviator.AviatorEvaluatorInstance.execute(AviatorEvaluatorInstance.java:1689)
	      at com.googlecode.aviator.AviatorEvaluatorInstance.execute(AviatorEvaluatorInstance.java:1700)
	      at com.googlecode.aviator.AviatorEvaluatorInstance.execute(AviatorEvaluatorInstance.java:1734)
	      at com.googlecode.aviator.test.function.FunctionTest.testSeqFunction(FunctionTest.java:489)
	      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	      at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	      at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	      at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	      at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	      at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	      at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	      at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	      at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	      at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	      at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	      at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	      at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	      at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	      at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	      at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	      at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	      at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	      at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	      at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	      at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	      at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	      at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	      at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	      at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	      at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	      at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	      at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
      Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make public final java.lang.Object java.util.HashMap$Node.getValue() accessible: module java.base does not "opens java.util" to unnamed module @6576fe71
	      at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	      at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	      at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	      at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	      at com.googlecode.aviator.utils.Reflector.getClassInstanceMethods(Reflector.java:549)
	      at com.googlecode.aviator.utils.Reflector.getInstanceMethods(Reflector.java:524)
	      at com.googlecode.aviator.utils.Reflector.retrieveGetterHandle(Reflector.java:321)
	      at com.googlecode.aviator.utils.Reflector.fastGetProperty(Reflector.java:239)
	      at com.googlecode.aviator.utils.Reflector.fastGetProperty(Reflector.java:833)
	      at com.googlecode.aviator.runtime.type.AviatorJavaType.getProperty(AviatorJavaType.java:455)
	      ... 43 more

**Comment by killme2008** [comment]
https://stackoverflow.com/questions/77980473/error-module-java-base-does-not-opens-java-util
