### ISSUE TITLE
FunctionNotFoundException 

### ISSUE THREAD

**Issue by Hendiaome** [killme2008/aviatorscript#641]
我的集群，有时候启动的时候会报这个错，com.googlecode.aviator.exception.FunctionNotFoundException: Function not found: list.contains
	at com.googlecode.aviator.RuntimeFunctionDelegator.getFunc(RuntimeFunctionDelegator.java:328) ~[aviator-5.2.6.jar:?]
	at com.googlecode.aviator.RuntimeFunctionDelegator.call(RuntimeFunctionDelegator.java:64) ~[aviator-5.2.6.jar:?]
	at Script_1723446112789_58/331705019.execute0(Script_1723446112789_58:1) ~[?:?]
	at com.googlecode.aviator.ClassExpression.executeDirectly(ClassExpression.java:67) ~[aviator-5.2.6.jar:?]
	at com.googlecode.aviator.BaseExpression.execute(BaseExpression.java:212) ~[aviator-5.2.6.jar:?]
	at com.googlecode.aviator.AviatorEvaluatorInstance.execute(AviatorEvaluatorInstance.java:1603) ~[aviator-5.2.6.jar:?]

重启一下就好了，并且我已经注册了list.contains这个函数，并且com.googlecode.aviator.AviatorEvaluatorInstance#addStaticFunctions返回值日志已经打印了加载到了list.contains这个函数，每次遇到重启就好了，这是什么问题呢

**Comment by killme2008** [comment]
确保脚本是在函数添加后编译或执行，应该是程序顺序问题。
